_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 6
DATASETS:
  TRAIN: ("parcel2d_demo_train", )
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  GAMMA: 0.25
  LR_SCHEDULER_NAME: WarmupCosineLR
  WARMUP_METHOD: linear
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 500
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "./output/demo"
