_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  DEVICE: cpu
  RESNETS:
    DEPTH: 50
  BACKBONE:
    FREEZE_AT: 6
DATALOADER:
  NUM_WORKERS: 0
DATASETS:
  TRAIN: ("parcel2d_demo_train", )
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  WARMUP_ITERS: 0
  MAX_ITER: 2
OUTPUT_DIR: "./output/unittest"
